version: '3.3'
services:
  dev:
    container_name: nestjs_api_dev
    image: nestjs-api-dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${APP_PORT}:${APP_PORT}
      - 3001:9229
    env_file:
      - .env
    networks:
      - nesjs-network
    depends_on:
      - coffeexmongo
    restart: unless-stopped
  coffeexmongo:
    image: mongo:latest
    container_name: coffeexmongo
    volumes:
      - ./database:/data/weatherdb
    ports:
      - 27017:27017
    networks:
      - nesjs-network
    restart: always
  prod:
    container_name: nestjs_api_prod
    image: nestjs-api-prod:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - ${APP_PORT}:${APP_PORT}
      - 9229:9229
    networks:
      - nesjs-network
    depends_on:
      - coffeexmongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
  test:
    container_name: nestjs_api_test
    image: nestjs-api-test:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run test
    ports:
      - ${APP_PORT}:${APP_PORT}
      - 9229:9229
    networks:
      - nesjs-network
    depends_on:
      - coffeexmongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
networks:
  nesjs-network:
    driver: bridge
